In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('Car Dataset Processed.csv')

In [3]:
df.head()

,Unnamed: 0,car_name,registration_year,insurance_validity,fuel_type,seats,kms_driven,ownsership,transmission,manufacturing_year,mileage(kmpl),engine(cc),max_power(bhp),torque(Nm),price(in lakhs)
0,0,2017 Mercedes-Benz S-Class S400,Jul-17,Comprehensive,Petrol,5,56000,First Owner,Automatic,2017,7.81,2996.0,2996.0,333.0,63.75
1,1,2020 Nissan Magnite Turbo CVT XV Premium Opt BSVI,Jan-21,Comprehensive,Petrol,5,30615,First Owner,Automatic,2020,17.40,999.0,999.0,9863.0,8.99
2,2,2018 BMW X1 sDrive 20d xLine,Sep-18,Comprehensive,Diesel,5,24000,First Owner,Automatic,2018,20.68,1995.0,1995.0,188.0,23.75
3,3,2019 Kia Seltos GTX Plus,Dec-19,Comprehensive,Petrol,5,18378,First Owner,Manual,2019,16.50,1353.0,1353.0,13808.0,13.56
4,4,2019 Skoda Superb LK 1.8 TSI AT,Aug-19,Comprehensive,Petrol,5,44900,First Owner,Automatic,2019,14.67,1798.0,1798.0,17746.0,24.00

In [4]:
df['insurance_validity'].value_counts()

insurance_validity
Comprehensive            1081
Third Party insurance     289
Zero Dep                   64
Third Party                63
Not Available               2
Name: count, dtype: int64

In [5]:
d1={'Comprehensive':0,'Third Party insurance':1,'Zero Dep':2,'Third Party':1,'Not Available':3}
df['insurance_validity']=df['insurance_validity'].map(d1)

In [6]:
df.head()

,Unnamed: 0,car_name,registration_year,insurance_validity,fuel_type,seats,kms_driven,ownsership,transmission,manufacturing_year,mileage(kmpl),engine(cc),max_power(bhp),torque(Nm),price(in lakhs)
0,0,2017 Mercedes-Benz S-Class S400,Jul-17,0,Petrol,5,56000,First Owner,Automatic,2017,7.81,2996.0,2996.0,333.0,63.75
1,1,2020 Nissan Magnite Turbo CVT XV Premium Opt BSVI,Jan-21,0,Petrol,5,30615,First Owner,Automatic,2020,17.40,999.0,999.0,9863.0,8.99
2,2,2018 BMW X1 sDrive 20d xLine,Sep-18,0,Diesel,5,24000,First Owner,Automatic,2018,20.68,1995.0,1995.0,188.0,23.75
3,3,2019 Kia Seltos GTX Plus,Dec-19,0,Petrol,5,18378,First Owner,Manual,2019,16.50,1353.0,1353.0,13808.0,13.56
4,4,2019 Skoda Superb LK 1.8 TSI AT,Aug-19,0,Petrol,5,44900,First Owner,Automatic,2019,14.67,1798.0,1798.0,17746.0,24.00

In [7]:
df['fuel_type'].value_counts()

fuel_type
Petrol    997
Diesel    480
CNG        22
Name: count, dtype: int64

In [8]:
d2={'Petrol':0,'Diesel':1,'CNG':2}
df['fuel_type']=df['fuel_type'].map(d2)

In [9]:
df['fuel_type'].value_counts()

fuel_type
0    997
1    480
2     22
Name: count, dtype: int64

In [10]:
df['ownsership'].value_counts()

ownsership
First Owner     1236
Second Owner     240
Third Owner       21
Fifth Owner        2
Name: count, dtype: int64

In [11]:
d3={'First Owner':1,'Second Owner':2,'Third Owner':3,'Fifth Owner':5,'Fourth Owner':4}
df['ownsership']=df['ownsership'].map(d3)

In [12]:
df['ownsership'].value_counts()

ownsership
1    1236
2     240
3      21
5       2
Name: count, dtype: int64

In [13]:
df['transmission'].value_counts()

transmission
Manual       832
Automatic    667
Name: count, dtype: int64

In [14]:
d4={'Manual':0,'Automatic':1}
df['transmission']=df['transmission'].map(d4)

In [15]:
df.head()

,Unnamed: 0,car_name,registration_year,insurance_validity,fuel_type,seats,kms_driven,ownsership,transmission,manufacturing_year,mileage(kmpl),engine(cc),max_power(bhp),torque(Nm),price(in lakhs)
0,0,2017 Mercedes-Benz S-Class S400,Jul-17,0,0,5,56000,1,1,2017,7.81,2996.0,2996.0,333.0,63.75
1,1,2020 Nissan Magnite Turbo CVT XV Premium Opt BSVI,Jan-21,0,0,5,30615,1,1,2020,17.40,999.0,999.0,9863.0,8.99
2,2,2018 BMW X1 sDrive 20d xLine,Sep-18,0,1,5,24000,1,1,2018,20.68,1995.0,1995.0,188.0,23.75
3,3,2019 Kia Seltos GTX Plus,Dec-19,0,0,5,18378,1,0,2019,16.50,1353.0,1353.0,13808.0,13.56
4,4,2019 Skoda Superb LK 1.8 TSI AT,Aug-19,0,0,5,44900,1,1,2019,14.67,1798.0,1798.0,17746.0,24.00

In [16]:
df['registration_year'] = df['registration_year'].str[-2:].astype(int)

In [17]:
df.head()

,Unnamed: 0,car_name,registration_year,insurance_validity,fuel_type,seats,kms_driven,ownsership,transmission,manufacturing_year,mileage(kmpl),engine(cc),max_power(bhp),torque(Nm),price(in lakhs)
0,0,2017 Mercedes-Benz S-Class S400,17,0,0,5,56000,1,1,2017,7.81,2996.0,2996.0,333.0,63.75
1,1,2020 Nissan Magnite Turbo CVT XV Premium Opt BSVI,21,0,0,5,30615,1,1,2020,17.40,999.0,999.0,9863.0,8.99
2,2,2018 BMW X1 sDrive 20d xLine,18,0,1,5,24000,1,1,2018,20.68,1995.0,1995.0,188.0,23.75
3,3,2019 Kia Seltos GTX Plus,19,0,0,5,18378,1,0,2019,16.50,1353.0,1353.0,13808.0,13.56
4,4,2019 Skoda Superb LK 1.8 TSI AT,19,0,0,5,44900,1,1,2019,14.67,1798.0,1798.0,17746.0,24.00

In [18]:
x=df[['insurance_validity','fuel_type','kms_driven','ownership','transmission']]
y=df['price(in lakhs)']

KeyError: "['ownership'] not in index"

In [ ]:
x.head()

In [48]:
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR

In [53]:
models={'LinReg':LinearRegression(),
      'KNN-3':KNeighborsRegressor(),
      'SVM-Poly':SVR(kernel='poly')}
for name,model in models.items():
    model.fit(x,y)
    sc=model.score(x,y)
    print(name,sc)

LinReg 0.01881841973825704
KNN-3 0.38617442772784927
SVM-Poly -0.002159341825328953

In [55]:
final_model=models['KNN-3']

In [58]:
insurance_validity=input('insurance_validity')
fuel_type=input('fuel_type')
kms_driven=input('kms_driven')
ownsership=input('ownsership')
transmission=input('transmission')
insurance_validity=d1[insurance_validity]
fuel_type=d2[fuel_type]
transmission=d4[transmission]
ownsership=d3[ownsership]
kms_driven=int(kms_driven)

insurance_validity Zero Dep
fuel_type CNG
kms_driven 45000
ownsership First Owner
transmission Automatic

In [59]:
test=[[insurance_validity,fuel_type,kms_driven,ownsership,transmission]]
final_model.predict(test)

C:\Users\rajpr\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but KNeighborsRegressor was fitted with feature names
  warnings.warn(

array([16.07])

In [64]:
import pickle 
pickle.dump(final_model,open('final_model.pkl',"wb"))